function fstruct = build_example_e1()

    % y(1)
    fstruct(1).terms = struct( ...
        'Is', 1e-9, ...
        'coeff', [1 -1 0 0], ...
        'Vt', 0.025 ...
    );

    % y(2)
    fstruct(2).terms(1) = struct( ...
        'Is', 1e-9, ...
        'coeff', [0 -1 1 0], ...
        'Vt', 0.025 ...
    );

    fstruct(2).terms(2) = struct( ...
        'Is', 1e-9, ...
        'coeff', [0 0 0 1], ...
        'Vt', 0.025 ...
    );

    % y(3) = 0
    fstruct(3).terms = []; % no terms → zero
end